- name: Yum -> add EPEL
  yum: name=http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: Yum -> enable EPEL
  ini_file: dest=/etc/yum.repos.d/epel.repo
    section=epel
    option=enabled
    value=1